name: Deploy GitHub Pages (versión estable)
on:
  workflow_dispatch:
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: pages
  cancel-in-progress: false
jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (versión estable del 17 de septiembre)
        uses: actions/checkout@v4
        with:
          ref: 560a9a6ce0b0384eae6ee85e27748e639feb4f14
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload public
        uses: actions/upload-pages-artifact@v3
        with:
          path: public
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
